name: Build and Deploy

on:
  #push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    uses: ./.github/workflows/linting.yml

  build:
    needs: lint
    uses: ./.github/workflows/reusable-build.yml
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
  
  test:
    needs: build
    uses: ./.github/workflows/python-tests.yml
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
